name: group7
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.12
  - numpy
  - graphviz
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - biopython
  - snakemake
  - pip